### ISSUE TITLE
Operator overloading doesn't work when expression has float before measurement

### ISSUE THREAD

**Issue by pekpuglia** [vini-fda/u-calc#4]
Bug found with exp: g = 4 * math.pi ** 2 L/ T ** 2, where L and T are Measurements. First found in old master, before fix_create_args and feature_better_sigma. To reproduce, in python shell:
import math and measurement,
create 2 Measurements, L and T,
and perform calculation as above.

**Comment by vini-fda** [comment]
Just a bug label is enough.

Can you be more specific with the problem? What are you importing/what is your setup, why are you writing e.g. T2(did you mean T**2?) etc

**Comment by vini-fda** [comment]
Oh and also tag/explicitly say which version are you using. Is it master/HEAD or v0.0.2-alpha, for example?
